name: Build from source and deploy to master

on:
  push:
    branches:
      - source
    
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: ğŸ“‚ checkout
        uses: actions/checkout@v2

      - name: ğŸ’ setup node
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: ğŸ”¨ install dependencies & build site
      - run: npm install
      - run: npm run build

      - name: ğŸš€ deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.JEKYLL_PAT }}
          publish_dir: ./dist
          publish_branch: master
